# Generated by Django 2.2.3 on 2019-07-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=20)),
                ('gambar', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
